// Original reflections, not attributed quotations or literal Bible verses.
export const reflections = [
  'Que Dios bendiga el trabajo de tus manos y la intención de tu corazón.',
  'Empieza con gratitud. Lo pequeño también merece celebrarse.',
  'Haz lo que esté en tus manos y entrega a Dios lo que no puedes controlar.',
  'Que hoy encuentres paz en lo sencillo y alegría en lo compartido.',
  'El esfuerzo de cada día también es una forma de esperanza.',
  'Trabajar con honestidad deja una huella que permanece.',
  'Un gesto amable puede cambiar el día de alguien.',
  'Dale tiempo a lo que estás construyendo con amor.',
  'Que la fe te acompañe en los comienzos y la paciencia en el camino.',
  'Hoy tienes otra oportunidad de hacer el bien.',
  'Cuida tus sueños con la misma ternura con la que cuidas a los tuyos.',
  'La gratitud nos ayuda a reconocer cuánto hemos recibido.',
  'No necesitas resolverlo todo hoy. Da el siguiente paso con calma.',
  'Que nunca te falten motivos para agradecer ni personas con quienes compartir.',
  'Pon amor en tu trabajo, incluso en lo que nadie ve.',
  'Una oración sencilla también puede ser un nuevo comienzo.',
  'Que María acompañe a tu familia y llene de paz tu hogar.',
  'La constancia transforma los pequeños pasos en un camino.',
  'Escuchar con atención es otra manera de servir.',
  'Que tus decisiones nazcan de la paz y de un corazón generoso.',
  'Celebra lo que has avanzado, aunque todavía falte camino.',
  'Siempre hay algo bueno que podemos ofrecer a los demás.',
  'Pedir ayuda también es una forma de seguir adelante.',
  'Que el cansancio encuentre descanso y la preocupación encuentre consuelo.',
  'Un día difícil no borra todo lo bueno que has construido.',
  'La esperanza también se cultiva con acciones pequeñas.',
  'Que tu trabajo sea sustento, encuentro y servicio.',
  'Agradece el pan de hoy y comparte cuando puedas.',
  'La bondad no necesita grandes ocasiones.',
  'Que San José inspire tu trabajo paciente y el cuidado de los tuyos.',
  'Puedes volver a empezar con lo que sabes ahora.',
  'Trata a cada persona con el respeto que quisieras recibir.',
  'En medio de las tareas, guarda un momento para respirar y agradecer.',
  'Que la alegría de servir te acompañe durante el día.',
  'Lo que haces con cuidado habla de lo que llevas en el corazón.',
  'Confía en Dios mientras sigues poniendo de tu parte.',
  'La paz también se construye con palabras amables.',
  'Que hoy puedas reconocer una bendición que ayer pasó desapercibida.',
  'Los buenos frutos necesitan raíces, cuidado y tiempo.',
  'Sé paciente contigo. Aprender también forma parte del trabajo.',
  'Que tu hogar sea refugio y tu trabajo una oportunidad para crecer.',
  'La generosidad empieza por estar disponible para alguien.',
  'Lleva contigo lo aprendido y deja espacio para lo nuevo.',
  'Que el amor de Dios te recuerde que tu valor va más allá de tus resultados.',
  'Un comienzo humilde puede guardar una historia hermosa.',
  'Que hoy haya espacio para el trabajo, el descanso y quienes amas.',
  'Cada encuentro es una oportunidad de tratar bien a alguien.',
  'Termina el día agradeciendo también lo que pudiste aprender.',
  'La luz de esta mañana también es una invitación a empezar.',
  'Hay días que florecen cuando los recibimos sin tanta prisa.',
  'Deja que una buena intención guíe tu primera tarea.',
  'Tu presencia puede ser el regalo que alguien necesita hoy.',
  'Un paso sereno vale más que una carrera sin rumbo.',
  'Mira con cariño lo que todavía está creciendo.',
  'El día puede traer sorpresas que aún no imaginas.',
  'Abre la puerta con esperanza y recibe con amabilidad.',
  'La vida se disfruta también en los momentos corrientes.',
  'Hoy puedes sembrar algo que mañana dará alegría.',
  'Agradece a quien hace más llevadero tu trabajo.',
  'Reconocer un favor pequeño engrandece el corazón.',
  'Hay abundancia en una mesa donde todos tienen lugar.',
  'Recuerda a las personas que te ayudaron a llegar hasta aquí.',
  'Una palabra de agradecimiento nunca llega demasiado tarde.',
  'Lo cotidiano guarda regalos que la prisa no deja ver.',
  'Disfruta lo que tienes mientras trabajas por lo que sueñas.',
  'El agradecimiento convierte una rutina en un encuentro.',
  'No des por sentado el cariño que te acompaña.',
  'Guarda memoria de las manos que te sostuvieron.',
  'Que Dios ilumine lo que hoy necesitas decidir.',
  'Puedes llevar tus inquietudes a la oración sin adornarlas.',
  'La fe deja una ventana abierta cuando todo parece cerrado.',
  'Dios también te encuentra en la sencillez de tu jornada.',
  'Pide sabiduría para actuar y humildad para escuchar.',
  'Que tu oración se vuelva una acción generosa.',
  'Descansa un momento en la certeza de que eres amado.',
  'Una fe pequeña puede acompañar un paso valiente.',
  'Que el silencio te ayude a escuchar lo que importa.',
  'Camina con confianza, aunque no veas todo el trayecto.',
  'La paciencia también es una forma de cuidar.',
  'No todas las flores se abren a la misma hora.',
  'Respeta el tiempo que necesita tu aprendizaje.',
  'Lo que madura despacio también puede llegar muy lejos.',
  'Un tropiezo merece atención, no una condena.',
  'Respira antes de responder cuando el día se complique.',
  'Hay respuestas que aparecen después de una pausa.',
  'El crecimiento no siempre hace ruido.',
  'Espera con esperanza y trabaja con dedicación.',
  'Trata tus propios procesos con un poco de ternura.',
  'La honestidad hace más ligero el descanso al final del día.',
  'Cumplir una promesa pequeña fortalece una gran confianza.',
  'Haz bien aquello que alguien puso en tus manos.',
  'La dignidad de tu trabajo está también en cómo lo haces.',
  'Ser justo empieza por los detalles de cada trato.',
  'Una decisión honesta puede cuidar muchas relaciones.',
  'Que tus palabras y tus acciones caminen juntas.',
  'Reconocer un error es el comienzo de repararlo.',
  'Cuida lo que te confían como cuidarías lo tuyo.',
  'La tranquilidad de actuar bien es una buena recompensa.',
  'Escuchar sin interrumpir puede aliviar un corazón.',
  'No sabes cuánto puede ayudar tu saludo de hoy.',
  'La amabilidad cabe en cualquier horario.',
  'Un trato respetuoso hace más agradable cualquier lugar.',
  'Ofrece la atención que te gustaría encontrar.',
  'La cortesía es una manera sencilla de compartir paz.',
  'Una sonrisa sincera puede abrir una conversación difícil.',
  'Recibe a los demás con espacio para su historia.',
  'Hablar con suavidad también es una muestra de fuerza.',
  'Que nadie se sienta invisible al pasar por tu lado.',
  'Tu familia merece también la mejor parte de tu atención.',
  'Un hogar se construye con gestos que se repiten con amor.',
  'Haz tiempo para preguntar cómo está alguien querido.',
  'Las conversaciones sencillas pueden guardar recuerdos enormes.',
  'Cuida los vínculos que te permiten ser tú mismo.',
  'Estar presente vale más que tener siempre la respuesta.',
  'El cariño también se expresa cumpliendo lo acordado.',
  'Una llamada breve puede acercar dos corazones.',
  'No hace falta una fecha especial para demostrar amor.',
  'Que al volver a casa encuentres un momento de calma.',
  'Descansar te ayuda a volver con una mirada más clara.',
  'Tu cuerpo merece el mismo cuidado que tus proyectos.',
  'Haz una pausa sin convertirla en culpa.',
  'Beber agua, respirar y estirarte también es cuidarte.',
  'No midas tu valor por cuánto logras hacer en un día.',
  'Dormir en paz también forma parte de avanzar.',
  'Escucha el cansancio antes de que te obligue a detenerte.',
  'Un rato de tranquilidad puede renovar tu paciencia.',
  'Deja espacio en tu agenda para recuperar fuerzas.',
  'Mereces cuidarte incluso cuando quedan tareas pendientes.',
  'Cada persona sabe algo que puede enseñarte.',
  'Una pregunta honesta abre caminos al aprendizaje.',
  'Aprender despacio sigue siendo aprender.',
  'No tengas vergüenza de volver a intentarlo.',
  'Lo que hoy cuesta puede volverse familiar con práctica.',
  'La curiosidad mantiene abiertas las posibilidades.',
  'Anota lo aprendido para regalarle claridad a tu mañana.',
  'Cambiar de opinión al aprender algo nuevo es crecer.',
  'Un consejo recibido con humildad puede ahorrarte un tropiezo.',
  'Celebra también aquello que ya haces mejor que antes.',
  'Compartir lo que sabes multiplica su valor.',
  'La generosidad no se mide solamente en dinero.',
  'Un poco de tu tiempo puede hacer una gran diferencia.',
  'Ayuda sin quitarle al otro la alegría de poder hacerlo.',
  'Dar con discreción también deja una huella profunda.',
  'Busca una manera pequeña de aliviar la carga de alguien.',
  'La bondad compartida encuentra nuevos caminos.',
  'Hay riqueza en saber acompañar.',
  'Ofrece lo que puedes, con cariño y sin compararte.',
  'Un acto de servicio puede darle sentido a tu día.',
  'La esperanza no exige tener todas las respuestas.',
  'Aun una jornada gris puede guardar un momento luminoso.',
  'Lo difícil de hoy no cuenta toda tu historia.',
  'Hay caminos que se descubren al seguir andando.',
  'Una puerta cerrada no termina con tus posibilidades.',
  'Confía en que todavía puedes aprender algo hermoso.',
  'La ilusión se cuida mejor con pasos concretos.',
  'Permítete imaginar un futuro amable.',
  'Cuando falte ánimo, apóyate en quienes te quieren.',
  'Un nuevo intento puede empezar con una decisión pequeña.',
  'Que María te enseñe a escuchar con un corazón disponible.',
  'Pon a tu familia bajo el cuidado de la Virgen.',
  'Que el ejemplo de San José te acompañe al trabajar.',
  'La oración puede ser un descanso en medio del ruido.',
  'Lleva al altar de tu corazón aquello que te preocupa.',
  'Que la misericordia se note en tu manera de tratar.',
  'Pide a Dios un corazón atento a quien necesita ayuda.',
  'La paz que buscas también puede comenzar en una oración.',
  'Que tu fe encuentre expresión en una obra buena.',
  'Recibe este día como una oportunidad de amar mejor.',
  'No necesitas competir con el camino de nadie.',
  'Tu historia tiene su propio ritmo y sus propias estaciones.',
  'La comparación pierde fuerza cuando reconoces tus avances.',
  'Celebra el bien de otros sin olvidar el tuyo.',
  'Tienes algo valioso que ofrecer desde quien eres.',
  'Tu esfuerzo merece respeto aunque nadie lo vea.',
  'Haz lugar para tus sueños sin despreciar tu presente.',
  'La sencillez puede ser una forma de plenitud.',
  'No todo lo importante necesita ser mostrado.',
  'La vida también crece lejos de los aplausos.',
  'Ordenar una tarea puede despejar una preocupación.',
  'Empieza por aquello que sí puedes resolver.',
  'Un pequeño compromiso cumplido te devuelve confianza.',
  'La constancia se construye un día a la vez.',
  'No abandones una buena idea por un primer intento difícil.',
  'Prepararte con cuidado hace más tranquilo el siguiente paso.',
  'Dedica tu atención a una cosa y hazla con cariño.',
  'El esfuerzo paciente deja aprendizajes duraderos.',
  'Revisa tu camino y ajusta lo necesario con serenidad.',
  'La disciplina también puede nacer del amor a lo que haces.',
  'Pedir perdón abre espacio para una relación más honesta.',
  'Escucha la herida antes de defender tu intención.',
  'Una disculpa sincera se acompaña de un cambio.',
  'Puedes poner límites sin perder la amabilidad.',
  'No cargues para siempre un error que ya estás reparando.',
  'El diálogo necesita tanto claridad como respeto.',
  'Que el orgullo no te robe una reconciliación posible.',
  'Cuidar la paz a veces requiere una conversación pendiente.',
  'Elige palabras que ayuden a comprenderse.',
  'La paciencia con otros empieza por reconocer nuestra fragilidad.',
  'Un equipo crece cuando todos pueden aportar.',
  'Reconoce el trabajo de quien suele pasar desapercibido.',
  'Compartir una responsabilidad puede fortalecer la confianza.',
  'Preguntar antes de suponer evita muchos desencuentros.',
  'Lo que se logra juntos merece celebrarse juntos.',
  'Un ambiente amable se construye entre todos.',
  'Sé la persona con quien resulte fácil colaborar.',
  'Una explicación clara también es un gesto de cuidado.',
  'Deja que las buenas ideas tengan más peso que el orgullo.',
  'La confianza se alimenta con hechos cotidianos.',
  'La alegría puede aparecer en una conversación breve.',
  'Permítete disfrutar de algo sencillo esta mañana.',
  'Un momento de risa también renueva las fuerzas.',
  'Busca belleza en un rincón que sueles ignorar.',
  'No guardes todas las celebraciones para el final.',
  'Hay días que mejoran con un poco de música.',
  'La satisfacción de una tarea bien hecha merece una pausa.',
  'Comparte una buena noticia con alguien que te quiera.',
  'La alegría no necesita que todo sea perfecto.',
  'Date permiso de sonreír mientras sigues aprendiendo.',
  'Caminar un momento puede ayudarte a ordenar tus ideas.',
  'Observa el cielo y recuerda que el día es más grande que tu pendiente.',
  'El aire fresco también puede ser una invitación a respirar mejor.',
  'Una planta cuidada nos enseña a esperar con atención.',
  'La naturaleza cambia sin pedirnos que corramos con ella.',
  'El sonido de la lluvia puede regalarte un instante de quietud.',
  'Mira cómo la luz encuentra su lugar al comenzar el día.',
  'Cuida el espacio que compartes con otros.',
  'La belleza de una flor no depende de quién la mire.',
  'Guarda un momento para agradecer la tierra que nos sostiene.',
  'Una dificultad puede mostrarte una fuerza que no conocías.',
  'Ser valiente también es reconocer que tienes miedo.',
  'Busca apoyo antes de sentir que debes poder con todo.',
  'No estás obligado a resolver cada problema a solas.',
  'Tu siguiente paso puede ser más pequeño de lo que imaginas.',
  'Sigue con cuidado; la prisa no es la única forma de avanzar.',
  'Una pausa a tiempo puede proteger un buen propósito.',
  'Las cicatrices también hablan de lo que has superado.',
  'Que la dificultad no te quite la ternura.',
  'Hay fortaleza en saber comenzar de nuevo con humildad.',
  'Que el Señor bendiga a quienes abren hoy su negocio.',
  'Pon en manos de Dios el fruto de tu esfuerzo.',
  'Una jornada de servicio puede ser una oración silenciosa.',
  'Que en tu trabajo haya justicia, cuidado y buen trato.',
  'Ofrece a Dios también las tareas que parecen pequeñas.',
  'La fe puede acompañarte mientras ordenas, atiendes y aprendes.',
  'Que tu sustento llegue unido a la paz de tu conciencia.',
  'Pide luz para distinguir lo urgente de lo importante.',
  'Que tus manos trabajen y tu corazón conserve la calma.',
  'Al cerrar el día, agradece lo recibido y lo aprendido.',
  'Trata con respeto incluso a quien piensa distinto.',
  'No hace falta ganar cada conversación para conservar tu dignidad.',
  'Una diferencia puede ser ocasión para comprender mejor.',
  'Habla con claridad sin lastimar innecesariamente.',
  'El respeto se demuestra también cuando nadie está mirando.',
  'Antes de juzgar, recuerda cuánto desconoces del otro.',
  'La empatía comienza al hacer espacio para otra mirada.',
  'Una respuesta serena puede cambiar el tono del encuentro.',
  'Dar la razón cuando corresponde también es sabiduría.',
  'Que tus convicciones convivan con un trato bondadoso.',
  'La sencillez deja espacio para disfrutar lo esencial.',
  'Un café compartido puede hacer más cálida la mañana.',
  'La riqueza de un día también está en quién te acompañó.',
  'No olvides disfrutar de aquello por lo que tanto trabajaste.',
  'El pan compartido sabe también a compañía.',
  'Una conversación sin distracciones puede ser un regalo.',
  'Ten cerca algo que te recuerde por qué empezaste.',
  'Un rincón ordenado puede invitar al descanso.',
  'Hay historias hermosas en los días que parecen iguales.',
  'La vida no necesita ser extraordinaria para ser querida.',
  'Cuida tus palabras: alguien puede recordarlas mucho tiempo.',
  'Di lo bueno que ves en quienes te rodean.',
  'Un reconocimiento sincero puede devolver entusiasmo.',
  'No reserves la ternura solamente para las ocasiones especiales.',
  'La verdad dicha con respeto ayuda a crecer.',
  'Pregunta con interés y escucha con paciencia.',
  'Una palabra de aliento puede acompañar más de lo que crees.',
  'El silencio atento también puede ser compañía.',
  'Que tu voz sea un lugar seguro para conversar.',
  'Expresar cariño es una forma de no darlo por sentado.',
  'El futuro se prepara con el cuidado que pones hoy.',
  'Un plan sencillo puede darle rumbo a una buena intención.',
  'No temas ajustar una meta cuando aprendes algo nuevo.',
  'Tus sueños merecen tiempo, atención y paciencia.',
  'Divide lo difícil en pasos que puedas comenzar.',
  'Lo que haces hoy puede facilitarle el camino a alguien mañana.',
  'La perseverancia también sabe cambiar de estrategia.',
  'Mantén cerca tu propósito y revisa tus prioridades.',
  'Trabaja con ilusión sin olvidarte de vivir el presente.',
  'Un progreso discreto sigue siendo un progreso real.',
  'Que la paz de Cristo te acompañe en tus encuentros.',
  'Deja un espacio para Dios entre tus planes.',
  'La caridad puede empezar por la persona más cercana.',
  'Que la oración te ayude a actuar con más compasión.',
  'Confía tus alegrías a Dios tanto como tus preocupaciones.',
  'La esperanza cristiana también invita a cuidar el presente.',
  'Pide un corazón capaz de agradecer y de compartir.',
  'Que María te acompañe en las tareas de este día.',
  'Recuerda en tu oración a quien atraviesa un momento difícil.',
  'El amor se vuelve visible cuando se convierte en servicio.',
  'La humildad te permite seguir aprendiendo de todos.',
  'Aceptar una corrección no borra lo que sabes hacer bien.',
  'Nadie llega lejos sin haber recibido ayuda.',
  'Reconocer tus límites puede acercarte a una solución.',
  'No necesitas aparentar certeza para merecer respeto.',
  'Un trabajo compartido deja espacio para aprender juntos.',
  'La experiencia crece cuando se une a la disposición de escuchar.',
  'Ser principiante también tiene la alegría del descubrimiento.',
  'Da gracias por quienes te enseñan con paciencia.',
  'El conocimiento es más valioso cuando se comparte con generosidad.',
  'Hay decisiones que mejoran después de una noche de descanso.',
  'No conviertas una mala hora en una sentencia para todo el día.',
  'Deja que la calma tenga una oportunidad antes de decidir.',
  'Una preocupación se hace más llevadera al ponerla en palabras.',
  'Puedes atender lo importante sin maltratarte en el proceso.',
  'El equilibrio se busca con pequeños ajustes cotidianos.',
  'No llenes tanto tu jornada que no quepa un encuentro.',
  'Aprende a reconocer cuándo necesitas parar.',
  'La serenidad se practica también en medio del trabajo.',
  'Hoy basta con dar un paso honesto en la dirección correcta.',
  'Recibe con cariño a quien regresa.',
  'La fidelidad se construye cuidando los detalles de cada encuentro.',
  'Cumple lo ofrecido y explica con honestidad lo que no puedes hacer.',
  'Una buena atención empieza por comprender la necesidad del otro.',
  'Que cada persona encuentre respeto al cruzar tu puerta.',
  'La confianza crece cuando hay claridad en el trato.',
  'Sirve con alegría y conserva el cuidado por lo pequeño.',
  'Una despedida amable deja abierta la posibilidad de volver.',
  'El buen nombre de un lugar se construye día tras día.',
  'Detrás de cada compra hay una persona que merece atención.',
  'Celebra los logros de quienes caminan contigo.',
  'La amistad se alimenta de interés y presencia.',
  'Una ayuda ofrecida a tiempo puede aliviar una semana entera.',
  'Haz saber a alguien que aprecias su compañía.',
  'Los vínculos se fortalecen cuando también sabemos escuchar.',
  'La distancia se hace menor con un gesto de cariño.',
  'Hay personas que hacen hogar dondequiera que estén.',
  'Cuida las amistades que te ayudan a ser mejor.',
  'Un recuerdo compartido puede alegrar la tarde.',
  'Que tu gratitud encuentre hoy a su destinatario.',
  'Cada estación tiene algo que enseñarnos.',
  'Dejar atrás una etapa también puede ser un acto de confianza.',
  'Conserva lo aprendido sin quedarte atado a lo que terminó.',
  'Los cambios se atraviesan mejor con compañía.',
  'Da la bienvenida a lo nuevo con prudencia y esperanza.',
  'Puedes extrañar lo vivido y abrirte a lo que viene.',
  'No todos los finales son una pérdida.',
  'Hay comienzos que llegan vestidos de incertidumbre.',
  'Toma de ayer la lección y deja espacio para hoy.',
  'La vida puede sorprenderte también después de un cambio.',
  'Que esta jornada te encuentre dispuesto a hacer el bien.',
  'Agradece una oportunidad que antes deseabas tener.',
  'Mira tus avances con justicia y tus pendientes con calma.',
  'La ternura también tiene lugar en un día de trabajo.',
  'Regala atención completa a una persona por unos minutos.',
  'Deja algo mejor de como lo encontraste.',
  'Que la bondad sea parte de lo que recuerden de ti.',
  'Lo que compartes con amor puede llegar más lejos que tú.',
  'Un corazón agradecido reconoce compañía en el camino.',
  'Tu esfuerzo de hoy puede ser alivio para quienes amas.',
  'Guarda un momento de paz antes de volver a empezar.',
  'Que no te falte humildad para aprender ni ánimo para continuar.',
  'La esperanza se renueva al reconocer el bien que aún es posible.',
  'Haz espacio para un gesto que no espere recompensa.',
  'La bendición de un día también puede estar en su sencillez.',
  'Recuerda con cariño a quien te enseñó a trabajar.',
  'Cierra la jornada con gratitud y abre la siguiente con confianza.',
]

// One calendar entry per day in Nicaragua, shared by every screen and device.
// February 29 uses December 31's entry; the other dates keep their usual entry.
export function dailyReflection(date = new Date()) {
  const parts = new Intl.DateTimeFormat('en-US', {
    timeZone: 'America/Managua',
    month: 'numeric',
    day: 'numeric',
  }).formatToParts(date)
  const month = Number(parts.find((part) => part.type === 'month')!.value)
  const day = Number(parts.find((part) => part.type === 'day')!.value)
  const starts = [0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334]
  const index = month === 2 && day === 29 ? 364 : starts[month - 1] + day - 1
  return reflections[index]
}
